# ci for product catlog servise


name: product-catalog-service-ci

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build
        run: |
          cd src/product-catalog
          go mod download
          go build -o product-catalog main.go

  code-quality:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Run unit tests
        run: |
          cd src/product-catalog-service
          go test -v ./...

  code-qualit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: 'v1.42.0'
          working-directory: src/product-catalog-service

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/product-catalog-service
          file: src/product-catalog-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}

  updatek8s:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update tag in Kubernetes deployment manifest
        run: |
          sed -i 's|image:.*|image:sumit-1777/ultimate-devops-project-demo: "${{ secrets.DOCKER_USERNAME }}"/product-catalog:${{ github.run_id }}|g' src/product-catalog-service/kubernetes/deployment.yaml
          echo "Updated image tag in deployment.yaml"

      - name: Commit changes
        run: |
          git config --local user.email "bansodesumit717@gmail.com"
          git config --local user.name "Sumit Bansode"
          git add src/product-catalog-service/kubernetes/deployment.yaml
          git commit -m "[ci]: update product-catalog image tag"
          git push origin main -f
